apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: baragae
  name: test-time
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-time
  template:
    metadata:
      labels:
        app: test-time
    spec:
      imagePullSecrets:
        - name: pwz-secret
      containers:
        - name: test-time
          env:
            - name: ENV
              value: prod
          image: baragae/imagename
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
